server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bulbach/cloud-config-app-server.git
          username: Bulbach
          password: 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
          default-label: main
          search-paths: "{application}"

 #          uri: file://path/to/local/resources/config
#          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